# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Tien Tong"
description: > # this means to ignore newlines until "email:"
   PhD Candidate - Neuroscience Program, University of Iowa

email: tien.tong98@gmail.com
#blog logo
logo: "/assets/images/Iowa_Hawkeyes_logo.svg.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/artificial-intelligence-3382507_1280.jpg"

name: 'Tien Tong'
author: 'Tien Tong'
author_image: "/assets/images/TongTCropped.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@tientong04'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/tientong04
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/tientong98
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
